### ISSUE TITLE
icon themes are just too powerful, apparently

### ISSUE THREAD

**Issue by cobalt2727** [geoffrey45/swingmusic#100]
I guess I brought this on myself...

```python
  -------------------------------------
  Swing v0.0.1.alpha 
  Started app on: http://localhost:1970
  -------------------------------------


[00:40:32]@swing • ✅ started watchdog
 * Serving Flask app 'app.api' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Loading tracks: 0it [00:00, ?it/s]
Processing folders: 0it [00:00, ?it/s]
Loading albums: 0it [00:00, ?it/s]
Mapping album colors: 0it [00:00, ?it/s]
Loading artists: 0it [00:00, ?it/s]
Removing deleted tracks: 0it [00:00, ?it/s]
Exception in thread Thread-7 (run_periodic_checks):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "app/functions.py", line 27, in run_periodic_checks
  File "app/lib/populate.py", line 30, in __init__
  File "app/utils.py", line 48, in run_fast_scandir
  File "app/utils.py", line 48, in run_fast_scandir
  File "app/utils.py", line 48, in run_fast_scandir
  [Previous line repeated 1 more time]
  File "app/utils.py", line 39, in run_fast_scandir
OSError: [Errno 40] Too many levels of symbolic links: '/home/cobalt/Tela-circle-icon-theme/links/scalable/apps/shortcuts.svg'
```

**Comment by geoffrey45** [comment]
This happens because the app scans all directories in your `~/` path for music. There's work in progress  for the next release that can resolve this. ie. You'll select the paths you want to scan for music files.

Thanks for the bug report.

**Comment by cobalt2727** [comment]
Thanks for the quick reply!
